services:
  app:
    build: .
    ports:
      - "1010:1010"
    develop:
      watch:
        - action: sync
          path: .
          target: /src/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - NOTION_KEY=${NOTION_KEY}
      - NOTION_ORDER_ITEMS_DB_ID=${NOTION_ORDER_ITEMS_DB_ID}
      - NOTION_EXTRA_COSTS_DB_ID=${NOTION_EXTRA_COSTS_DB_ID}

