services:
  app:
    build: .
    ports:
      - "1010:1010"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
