import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import FullPageHeader from "@/components/layout/FullPageHeader";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <div className="z-10 absolute top-0 w-full">
          <FullPageHeader />
        </div>
        <main className="flex-1 w-full">
          <MantineProvider>{children}</MantineProvider>
        </main>
        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
